In [2]:
import pandas as pd

df_1 = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['Student 1', 'Student 2', 'Student 3']
}).convert_dtypes(dtype_backend='pyarrow')

df_2 = pd.DataFrame({
    'id': [4, 5, 6],
    'name': ['Student 4', 'Student 5', 'Student 6']
}).convert_dtypes(dtype_backend='pyarrow')

df = pd.concat([df_1, df_2])
df

   id       name
0   1  Student 1
1   2  Student 2
2   3  Student 3
0   4  Student 4
1   5  Student 5
2   6  Student 6

<h1>Duplicate indices do not affect the result of loc[]</h1>

In [4]:
df.loc[df['id'].isin([1, 2, 3]), :]

   id       name
0   1  Student 1
1   2  Student 2
2   3  Student 3