In [6]:
import pandas as pd
from datetime import datetime, timezone, timedelta
from zoneinfo import ZoneInfo

In [29]:
t_1 = datetime.now(timezone.utc)
t_2 = t_utc + timedelta(hours=1)

(t_1, t_2)

(datetime.datetime(2026, 9, 7, 1, 14, 43, 812586, tzinfo=datetime.timezone.utc),
 datetime.datetime(2026, 9, 7, 2, 14, 7, 439918, tzinfo=datetime.timezone.utc))

In [32]:
df = pd.DataFrame({
    'id': [1, 2],
    'value': [t_1, t_2]
})

df = df.convert_dtypes(dtype_backend="pyarrow")
df.info()

df

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      2 non-null      int64[pyarrow]
 1   value   2 non-null      timestamp[us, tz=UTC][pyarrow]
dtypes: int64[pyarrow](1), timestamp[us, tz=UTC][pyarrow](1)
memory usage: 164.0 bytes

   id                             value
0   1  2026-09-07 01:14:43.812586+00:00
1   2  2026-09-07 02:14:07.439918+00:00

<b>Only tz_convert is allowed if the column is already timestamp[us, tz=UTC]</b>
<br>
<b>tz_localize is not allowed</b>

In [36]:
df = pd.DataFrame({
    'id': [1, 2],
    'value': [t_1, t_2]
})

df = df.convert_dtypes(dtype_backend="pyarrow")
df['value'] = df['value'].dt.tz_convert(ZoneInfo("America/New_York"))
df

   id                             value
0   1  2026-09-06 21:14:43.812586-04:00
1   2  2026-09-06 22:14:07.439918-04:00